export const SERVER_ERROR = {
	WISHLIST_NOT_FOUND: 'WISHLIST_NOT_FOUND',
	ONLY_OWNER_CAN_MANAGE_MODERATORS: 'ONLY_OWNER_CAN_MANAGE_MODERATORS',
	ACCESS_DENIED: 'ACCESS_DENIED',
	FAILED_TO_CREATE_INVITE: 'FAILED_TO_CREATE_INVITE',
	INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
	INVITE_ALREADY_REVOKED: 'INVITE_ALREADY_REVOKED',
	INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
	OWNER_CANNOT_ACCEPT_OWN_INVITE: 'OWNER_CANNOT_ACCEPT_OWN_INVITE',
	ALREADY_MODERATOR: 'ALREADY_MODERATOR',
	FAILED_TO_ASSIGN_MODERATOR: 'FAILED_TO_ASSIGN_MODERATOR',
	MODERATOR_NOT_FOUND: 'MODERATOR_NOT_FOUND',
	ALREADY_SEEING_RESERVATIONS: 'ALREADY_SEEING_RESERVATIONS',

	GIFT_NOT_FOUND: 'GIFT_NOT_FOUND',
	CANNOT_RESERVE_ON_ARCHIVED: 'CANNOT_RESERVE_ON_ARCHIVED',
	OWNER_CANNOT_RESERVE_OWN_GIFTS: 'OWNER_CANNOT_RESERVE_OWN_GIFTS',
	ANONYMOUS_NAME_REQUIRED: 'ANONYMOUS_NAME_REQUIRED',
	QUANTITY_MUST_BE_AT_LEAST_ONE: 'QUANTITY_MUST_BE_AT_LEAST_ONE',
	NOT_ENOUGH_AVAILABLE: 'NOT_ENOUGH_AVAILABLE',
	RESERVATION_FAILED: 'RESERVATION_FAILED',
	RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
	CANNOT_CANCEL_OTHERS_RESERVATION: 'CANNOT_CANCEL_OTHERS_RESERVATION',
	ANONYMOUS_CANNOT_CANCEL_RESERVATIONS: 'ANONYMOUS_CANNOT_CANCEL_RESERVATIONS',
	CANNOT_CANCEL_ANONYMOUS_RESERVATION: 'CANNOT_CANCEL_ANONYMOUS_RESERVATION',

	OWNER_CANNOT_LIKE_OWN_GIFTS: 'OWNER_CANNOT_LIKE_OWN_GIFTS',

	FAILED_TO_CREATE_GIFT: 'FAILED_TO_CREATE_GIFT',
	CANNOT_EDIT_AFTER_SHARING: 'CANNOT_EDIT_AFTER_SHARING',
	CANNOT_DELETE_AFTER_SHARING: 'CANNOT_DELETE_AFTER_SHARING',
	CANNOT_DELETE_RESERVED_GIFT: 'CANNOT_DELETE_RESERVED_GIFT',
	ONLY_OWNER_CAN_MARK_RECEIVED: 'ONLY_OWNER_CAN_MARK_RECEIVED',

	CANNOT_MODIFY_ARCHIVED_WISHLIST: 'CANNOT_MODIFY_ARCHIVED_WISHLIST',
	CANNOT_LIKE_ON_ARCHIVED: 'CANNOT_LIKE_ON_ARCHIVED',
	CANNOT_SHARE_ARCHIVED_WISHLIST: 'CANNOT_SHARE_ARCHIVED_WISHLIST',
	CANNOT_INVITE_ON_ARCHIVED: 'CANNOT_INVITE_ON_ARCHIVED',
	CANNOT_SELF_PROMOTE_ON_ARCHIVED: 'CANNOT_SELF_PROMOTE_ON_ARCHIVED',
} as const;

export type ServerErrorCode = (typeof SERVER_ERROR)[keyof typeof SERVER_ERROR];

export function encodeServerError(
	code: ServerErrorCode,
	params: Record<string, string | number>,
): string {
	return JSON.stringify({ code, ...params });
}
