export const SERVER_ERROR = {
	WISHLIST_NOT_FOUND: 'WISHLIST_NOT_FOUND',
	ACCESS_DENIED: 'ACCESS_DENIED',
	FAILED_TO_CREATE_INVITE: 'FAILED_TO_CREATE_INVITE',
	INVITE_NOT_FOUND: 'INVITE_NOT_FOUND',
	INVITE_ALREADY_REVOKED: 'INVITE_ALREADY_REVOKED',
	INVITE_ALREADY_USED: 'INVITE_ALREADY_USED',
	RECIPIENT_CANNOT_ACCEPT_OWN_INVITE: 'RECIPIENT_CANNOT_ACCEPT_OWN_INVITE',
	ALREADY_MODERATOR: 'ALREADY_MODERATOR',
	FAILED_TO_ASSIGN_MODERATOR: 'FAILED_TO_ASSIGN_MODERATOR',
	MODERATOR_NOT_FOUND: 'MODERATOR_NOT_FOUND',
	CANNOT_REMOVE_LAST_MANAGER: 'CANNOT_REMOVE_LAST_MANAGER',
	ALREADY_SEEING_RESERVATIONS: 'ALREADY_SEEING_RESERVATIONS',

	// Claim invite (issue #150): link a free-text recipient's real account.
	CLAIM_NOT_FOR_LINKED_RECIPIENT: 'CLAIM_NOT_FOR_LINKED_RECIPIENT',
	CLAIM_ALREADY_LINKED: 'CLAIM_ALREADY_LINKED',
	CLAIM_EX_MANAGER: 'CLAIM_EX_MANAGER',
	CLAIM_HAS_RESERVATIONS: 'CLAIM_HAS_RESERVATIONS',

	GIFT_NOT_FOUND: 'GIFT_NOT_FOUND',
	CANNOT_RESERVE_ON_ARCHIVED: 'CANNOT_RESERVE_ON_ARCHIVED',
	RECIPIENT_CANNOT_RESERVE_OWN_GIFTS: 'RECIPIENT_CANNOT_RESERVE_OWN_GIFTS',
	ANONYMOUS_NAME_REQUIRED: 'ANONYMOUS_NAME_REQUIRED',
	TURNSTILE_REQUIRED: 'TURNSTILE_REQUIRED',
	TURNSTILE_INVALID: 'TURNSTILE_INVALID',
	TURNSTILE_EXPIRED_OR_REPLAYED: 'TURNSTILE_EXPIRED_OR_REPLAYED',
	TURNSTILE_UNAVAILABLE: 'TURNSTILE_UNAVAILABLE',
	QUANTITY_MUST_BE_AT_LEAST_ONE: 'QUANTITY_MUST_BE_AT_LEAST_ONE',
	NOT_ENOUGH_AVAILABLE: 'NOT_ENOUGH_AVAILABLE',
	RESERVATION_FAILED: 'RESERVATION_FAILED',
	RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
	CANNOT_CANCEL_OTHERS_RESERVATION: 'CANNOT_CANCEL_OTHERS_RESERVATION',
	ANONYMOUS_CANNOT_CANCEL_RESERVATIONS: 'ANONYMOUS_CANNOT_CANCEL_RESERVATIONS',
	CANNOT_CANCEL_ANONYMOUS_RESERVATION: 'CANNOT_CANCEL_ANONYMOUS_RESERVATION',

	RECIPIENT_CANNOT_LIKE_OWN_GIFTS: 'RECIPIENT_CANNOT_LIKE_OWN_GIFTS',

	FAILED_TO_CREATE_GIFT: 'FAILED_TO_CREATE_GIFT',
	CANNOT_EDIT_AFTER_SHARING: 'CANNOT_EDIT_AFTER_SHARING',
	QUANTITY_CANNOT_BE_LOWERED: 'QUANTITY_CANNOT_BE_LOWERED',
	CANNOT_DELETE_AFTER_SHARING: 'CANNOT_DELETE_AFTER_SHARING',
	DESCRIPTION_APPEND_NOT_FOUND: 'DESCRIPTION_APPEND_NOT_FOUND',
	CANNOT_DELETE_RESERVED_GIFT: 'CANNOT_DELETE_RESERVED_GIFT',
	GIFT_WISHLIST_MISMATCH: 'GIFT_WISHLIST_MISMATCH',

	RECIPIENT_RENAME_NOT_ALLOWED: 'RECIPIENT_RENAME_NOT_ALLOWED',
	FAILED_TO_CREATE_WISHLIST: 'FAILED_TO_CREATE_WISHLIST',
	CANNOT_MODIFY_ARCHIVED_WISHLIST: 'CANNOT_MODIFY_ARCHIVED_WISHLIST',
	CANNOT_LIKE_ON_ARCHIVED: 'CANNOT_LIKE_ON_ARCHIVED',
	CANNOT_SHARE_ARCHIVED_WISHLIST: 'CANNOT_SHARE_ARCHIVED_WISHLIST',
	CANNOT_INVITE_ON_ARCHIVED: 'CANNOT_INVITE_ON_ARCHIVED',
	CANNOT_SELF_PROMOTE_ON_ARCHIVED: 'CANNOT_SELF_PROMOTE_ON_ARCHIVED',

	SHEETS_LINK_INVALID: 'SHEETS_LINK_INVALID',
	SHEETS_LINK_NOT_A_SHEET: 'SHEETS_LINK_NOT_A_SHEET',
	SHEETS_PRIVATE: 'SHEETS_PRIVATE',
	SHEETS_FETCH_FAILED: 'SHEETS_FETCH_FAILED',
} as const;

export type ServerErrorCode = (typeof SERVER_ERROR)[keyof typeof SERVER_ERROR];

export function encodeServerError(
	code: ServerErrorCode,
	params: Record<string, string | number>,
): string {
	return JSON.stringify({ code, ...params });
}
