import type { Palette } from '$lib/theme/palettes.js';

export interface DemoCatalogWishlist {
	key: string;
	title: string;
	description: string;
	role: 'own' | 'managed' | 'followed';
	recipientName: string;
	status: 'draft' | 'shared' | 'archived';
	occasion: 'ongoing' | 'birthday' | 'christmas';
	palette: Palette;
	gifts: Array<{
		name: string;
		description: string;
		imageUrl: string;
		url: string;
		price: number;
		category: string;
		priority: 'high' | 'medium' | 'low';
		state: 'available' | 'reserved' | 'received';
	}>;
}

type Localized = { cs: string; en: string };
type CatalogItem = {
	image: string;
	name: Localized;
	description: Localized;
	category: Localized;
	price: number;
	search: string;
};

const categories = {
	books: { cs: 'Knihy', en: 'Books' },
	tech: { cs: 'Elektronika', en: 'Electronics' },
	home: { cs: 'Domov', en: 'Home' },
	outdoors: { cs: 'Venku', en: 'Outdoors' },
	food: { cs: 'Jídlo a pití', en: 'Food and drink' },
	creative: { cs: 'Tvoření', en: 'Creative' },
	fashion: { cs: 'Oblečení a doplňky', en: 'Clothing and accessories' },
	games: { cs: 'Hry', en: 'Games' },
} satisfies Record<string, Localized>;

function item(
	image: string,
	nameCs: string,
	nameEn: string,
	descriptionCs: string,
	descriptionEn: string,
	category: Localized,
	price: number,
	search: string,
): CatalogItem {
	return {
		image,
		name: { cs: nameCs, en: nameEn },
		description: { cs: descriptionCs, en: descriptionEn },
		category,
		price,
		search,
	};
}

// Photos are category-accurate examples, not claims that the pictured object is the linked SKU.
const items = {
	teaPot: item(
		'v1/teapot.jpg',
		'Keramická konvička',
		'Ceramic teapot',
		'Na nedělní čaj ve dvou.',
		'For slow Sunday tea for two.',
		categories.home,
		690,
		'keramická čajová konvice',
	),
	headphones: item(
		'v1/headphones.jpg',
		'Bezdrátová sluchátka',
		'Wireless headphones',
		'Pohodlná sluchátka na cesty vlakem.',
		'Comfortable headphones for train journeys.',
		categories.tech,
		2490,
		'bezdrátová sluchátka přes uši',
	),
	journal: item(
		'v1/plant-book.jpg',
		'Zápisník na každý den',
		'Everyday journal',
		'Na nápady, které nechci zapomenout.',
		'For ideas I do not want to forget.',
		categories.books,
		350,
		'tečkovaný zápisník',
	),
	candle: item(
		'v1/candle.jpg',
		'Vonná svíčka',
		'Scented candle',
		'Jemná vůně na dlouhé večery.',
		'A gentle scent for long evenings.',
		categories.home,
		390,
		'vonná svíčka',
	),
	leatherBackpack: item(
		'v1/backpack.jpg',
		'Kožený batoh',
		'Leather backpack',
		'Jednoduchý batoh do města.',
		'A simple backpack for days in town.',
		categories.fashion,
		1800,
		'kožený batoh',
	),
	watercolours: item(
		'v1/watercolours.jpg',
		'Akvarelové barvy',
		'Watercolour paints',
		'Malá sada na víkendové malování.',
		'A little set for painting at the weekend.',
		categories.creative,
		480,
		'akvarelové barvy sada',
	),
	chocolates: item(
		'playground/advent.jpg',
		'Výběr pralinek',
		'Box of chocolates',
		'Různé příchutě ke společnému ochutnávání.',
		'An assortment to taste together.',
		categories.food,
		420,
		'dárková bonboniéra pralinky',
	),
	hikingBackpack: item(
		'playground/batoh.jpg',
		'Turistický batoh',
		'Hiking backpack',
		'Lehký batoh na celodenní výlety.',
		'A light pack for day hikes.',
		categories.outdoors,
		1590,
		'turistický batoh 25 l',
	),
	winterCoat: item(
		'playground/bunda.jpg',
		'Teplý zimní kabát',
		'Warm winter coat',
		'Do mrazivých ranních procházek.',
		'For frosty morning walks.',
		categories.fashion,
		2300,
		'zimní kabát',
	),
	looseTea: item(
		'playground/caj.jpg',
		'Sypaný čaj',
		'Loose-leaf tea',
		'Něco voňavého do nové konvičky.',
		'Something fragrant for the new teapot.',
		categories.food,
		280,
		'sypaný čaj dárková sada',
	),
	boardGame: item(
		'playground/catan.jpg',
		'Rodinná desková hra',
		'Family board game',
		'Ať máme co hrát při návštěvách.',
		'Something to play when friends visit.',
		categories.games,
		890,
		'desková hra pro rodinu',
	),
	watch: item(
		'playground/hodinky-d.jpg',
		'Klasické hodinky',
		'Classic watch',
		'Jednoduchý ciferník a kožený řemínek.',
		'A clean dial and a leather strap.',
		categories.fashion,
		1790,
		'analogové hodinky kožený řemínek',
	),
	handbag: item(
		'playground/kabelka.jpg',
		'Malá kabelka',
		'Small handbag',
		'Na klíče, telefon a drobnosti.',
		'Just big enough for keys and a phone.',
		categories.fashion,
		990,
		'malá kabelka přes rameno',
	),
	coffeeBeans: item(
		'playground/kavovar.jpg',
		'Zrnková káva',
		'Whole-bean coffee',
		'Středně pražená na domácí espresso.',
		'Medium-roast beans for home espresso.',
		categories.food,
		400,
		'zrnková káva 500 g',
	),
	eReader: item(
		'playground/kindle.jpg',
		'Čtečka knih',
		'E-reader',
		'Aby se do batohu vešlo víc příběhů.',
		'So more stories fit in one bag.',
		categories.tech,
		3490,
		'čtečka elektronických knih',
	),
	bicycle: item(
		'playground/kolo.jpg',
		'Městské kolo',
		'City bicycle',
		'Na cesty parkem místo tramvaje.',
		'For trips through the park instead of the tram.',
		categories.outdoors,
		8990,
		'městské kolo',
	),
	guitar: item(
		'playground/kytara.jpg',
		'Elektrická kytara',
		'Electric guitar',
		'Na první hraní s kapelou.',
		'For those first band rehearsals.',
		categories.creative,
		4990,
		'elektrická kytara',
	),
	flowers: item(
		'playground/kytice.jpg',
		'Kytice sezónních květin',
		'Seasonal flowers',
		'Pestrá kytice jen tak pro radost.',
		'A colourful bouquet just because.',
		categories.home,
		650,
		'kytice sezonní květiny',
	),
	standMixer: item(
		'playground/lampicka.jpg',
		'Robot KitchenAid',
		'KitchenAid stand mixer',
		'Na těsta, která se špatně míchají rukou.',
		'For dough that takes too long to mix by hand.',
		categories.home,
		11990,
		'robot KitchenAid Artisan',
	),
	buildingBricks: item(
		'playground/lego.jpg',
		'Stavebnice kostek',
		'Building bricks set',
		'Na společné stavění o prázdninách.',
		'For building together over the holidays.',
		categories.games,
		1190,
		'stavebnice kostky',
	),
	cake: item(
		'playground/mixer.jpg',
		'Čokoládový dort',
		'Chocolate cake',
		'Narozeninový dort pro celou rodinu.',
		'A birthday cake for the whole family.',
		categories.food,
		850,
		'čokoládový dort objednávka',
	),
	monitor: item(
		'playground/monitor.jpg',
		'Monitor k počítači',
		'Computer monitor',
		'Větší obrazovka k pracovnímu stolu.',
		'A larger screen for the desk.',
		categories.tech,
		4290,
		'monitor 27 palců',
	),
	monstera: item(
		'playground/monstera.jpg',
		'Monstera',
		'Monstera plant',
		'Zelený společník do obýváku.',
		'A leafy companion for the living room.',
		categories.home,
		590,
		'monstera pokojová rostlina',
	),
	fragrance: item(
		'playground/parfem.jpg',
		'Svěží parfém',
		'Fresh fragrance',
		'Lehká vůně na každý den.',
		'A light scent for everyday wear.',
		categories.fashion,
		1490,
		'svěží parfém',
	),
	socks: item(
		'playground/ponozky.jpg',
		'Veselé ponožky',
		'Colourful socks',
		'Pár barev do zimních bot.',
		'A splash of colour for winter boots.',
		categories.fashion,
		240,
		'barevné ponožky dárkové',
	),
	restaurant: item(
		'playground/poukaz.jpg',
		'Večeře pro dva',
		'Dinner for two',
		'Večer bez vaření a mytí nádobí.',
		'An evening without cooking or washing up.',
		categories.food,
		1800,
		'dárkový poukaz restaurace',
	),
	console: item(
		'playground/ps5.jpg',
		'Herní konzole PlayStation 5',
		'PlayStation 5 console',
		'Na společné hraní o víkendech.',
		'For playing together at weekends.',
		categories.tech,
		11990,
		'PlayStation 5 konzole',
	),
	chess: item(
		'playground/sachy.jpg',
		'Šachová sada',
		'Chess set',
		'Dřevěná šachovnice na dlouhé partie.',
		'A wooden board for long games.',
		categories.games,
		690,
		'dřevěné šachy sada',
	),
	readingBook: item(
		'playground/sapiens.jpg',
		'Kniha o světě kolem nás',
		'A book about our world',
		'Zajímavé čtení ke kávě.',
		'Interesting reading over a cup of coffee.',
		categories.books,
		420,
		'populárně naučná kniha',
	),
	shawl: item(
		'playground/satek.jpg',
		'Lehký šátek',
		'Lightweight scarf',
		'Na větrné dny u vody.',
		'For breezy days by the water.',
		categories.fashion,
		490,
		'lehký šátek',
	),
	wineGlasses: item(
		'playground/sklenice.jpg',
		'Sklenice na víno',
		'Wine glasses',
		'Nové sklenice na oslavy s přáteli.',
		'New glasses for celebrations with friends.',
		categories.home,
		690,
		'sklenice na víno sada',
	),

	tent: item(
		'playground/stan.jpg',
		'Stan pro dva',
		'Two-person tent',
		'Na letní noci pod hvězdami.',
		'For summer nights under the stars.',
		categories.outdoors,
		2290,
		'stan pro dva',
	),
} satisfies Record<string, CatalogItem>;

type ItemKey = keyof typeof items;
type WishlistDefinition = Omit<DemoCatalogWishlist, 'title' | 'description' | 'gifts'> & {
	title: Localized;
	description: Localized;
	itemKeys: readonly ItemKey[];
};

const wishlists: readonly WishlistDefinition[] = [
	{
		key: 'my-everyday',
		title: { cs: 'Malé radosti', en: 'Little everyday joys' },
		description: {
			cs: 'Pár nápadů pro obyčejné i slavnostní dny.',
			en: 'A few ideas for ordinary days and special ones.',
		},
		role: 'own',
		recipientName: 'Tereza Novotná',
		status: 'shared',
		occasion: 'ongoing',
		palette: 'sky',
		itemKeys: [
			'teaPot',
			'journal',
			'candle',
			'watercolours',
			'looseTea',
			'coffeeBeans',
			'eReader',
			'flowers',
			'monstera',
			'socks',
			'readingBook',
			'shawl',
			'wineGlasses',
			'headphones',
			'handbag',
		],
	},
	{
		key: 'my-birthday',
		title: { cs: 'Tereziny narozeniny', en: "Tereza's birthday" },
		description: {
			cs: 'Letos bych ráda zkusila něco nového.',
			en: 'This year I would love to try something new.',
		},
		role: 'own',
		recipientName: 'Tereza Novotná',
		status: 'shared',
		occasion: 'birthday',
		palette: 'peach',
		itemKeys: [
			'headphones',
			'hikingBackpack',
			'watch',
			'bicycle',
			'guitar',
			'cake',
			'monitor',
			'fragrance',
			'restaurant',
			'console',
			'chess',
			'candle',
			'tent',
			'buildingBricks',
			'standMixer',
		],
	},
	{
		key: 'my-christmas-draft',
		title: { cs: 'Vánoční nápady', en: 'Christmas ideas' },
		description: {
			cs: 'Zatím si sem ukládám tipy pro rodinu.',
			en: 'Saving ideas here for the family for now.',
		},
		role: 'own',
		recipientName: 'Tereza Novotná',
		status: 'draft',
		occasion: 'christmas',
		palette: 'grape',
		itemKeys: [
			'chocolates',
			'winterCoat',
			'looseTea',
			'boardGame',
			'handbag',
			'eReader',
			'buildingBricks',
			'monitor',
			'socks',
			'fragrance',
			'chess',
			'teaPot',
			'readingBook',
			'tent',
			'coffeeBeans',
		],
	},
	{
		key: 'mum-christmas',
		title: { cs: 'Vánoce pro maminku', en: 'Christmas for Mum' },
		description: {
			cs: 'Nápady od celé rodiny pro paní Alenu.',
			en: 'Ideas from the whole family for Alena.',
		},
		role: 'managed',
		recipientName: 'Alena Novotná',
		status: 'shared',
		occasion: 'christmas',
		palette: 'sakura',
		itemKeys: [
			'teaPot',
			'journal',
			'candle',
			'chocolates',
			'looseTea',
			'handbag',
			'coffeeBeans',
			'flowers',
			'standMixer',
			'monstera',
			'fragrance',
			'restaurant',
			'shawl',
			'wineGlasses',
			'readingBook',
		],
	},
	{
		key: 'nephew-birthday',
		title: { cs: 'Matějovy narozeniny', en: "Matěj's birthday" },
		description: {
			cs: 'Dárky k oslavě, kterou chystáme společně.',
			en: 'Gifts for the party we are planning together.',
		},
		role: 'managed',
		recipientName: 'Matěj Veselý',
		status: 'shared',
		occasion: 'birthday',
		palette: 'honey',
		itemKeys: [
			'headphones',
			'watercolours',
			'boardGame',
			'hikingBackpack',
			'bicycle',
			'guitar',
			'buildingBricks',
			'cake',
			'socks',
			'console',
			'chess',
			'candle',
			'tent',
			'journal',
			'chocolates',
		],
	},
	{
		key: 'friend-everyday',
		title: { cs: 'Petrův seznam na cesty', en: "Petr's travel wishlist" },
		description: {
			cs: 'Petr sbírá tipy na další výpravy.',
			en: 'Petr is collecting ideas for his next adventures.',
		},
		role: 'followed',
		recipientName: 'Petr Dvořák',
		status: 'shared',
		occasion: 'ongoing',
		palette: 'mint',
		itemKeys: [
			'hikingBackpack',
			'winterCoat',
			'eReader',
			'bicycle',
			'monitor',
			'socks',
			'restaurant',
			'candle',
			'tent',
			'guitar',
			'watch',
			'headphones',
			'coffeeBeans',
			'chess',
			'shawl',
		],
	},
	{
		key: 'friend-christmas',
		title: { cs: 'Vánoce u Kláry', en: "Christmas at Klára's" },
		description: {
			cs: 'Klára má ráda knihy, tvoření a útulný domov.',
			en: 'Klára loves books, crafts and a cosy home.',
		},
		role: 'followed',
		recipientName: 'Klára Horáková',
		status: 'shared',
		occasion: 'christmas',
		palette: 'ruby',
		itemKeys: [
			'teaPot',
			'journal',
			'candle',
			'watercolours',
			'chocolates',
			'looseTea',
			'handbag',
			'coffeeBeans',
			'flowers',
			'standMixer',
			'monstera',
			'readingBook',
			'shawl',
			'wineGlasses',
			'boardGame',
		],
	},
	{
		key: 'grandpa-birthday',
		title: { cs: 'Dědovy narozeniny', en: "Grandad's birthday" },
		description: {
			cs: 'Vzpomínka na povedenou rodinnou oslavu.',
			en: 'Remembering a lovely family celebration.',
		},
		role: 'followed',
		recipientName: 'Karel Veselý',
		status: 'archived',
		occasion: 'birthday',
		palette: 'ocean',
		itemKeys: [
			'teaPot',
			'journal',
			'looseTea',
			'boardGame',
			'watch',
			'coffeeBeans',
			'cake',
			'monstera',
			'restaurant',
			'chess',
			'readingBook',
			'wineGlasses',
			'candle',
			'tent',
			'chocolates',
		],
	},
];

export const preparedDemoImageUrls = new Set(
	Object.values(items).map((catalogItem) => `/demo/${catalogItem.image}`),
);

export function getDemoCatalog(locale: 'cs' | 'en'): DemoCatalogWishlist[] {
	return wishlists.map(({ itemKeys, title, description, ...wishlist }) => ({
		...wishlist,
		title: title[locale],
		description: description[locale],
		gifts: itemKeys.map((key, index) => {
			const gift = items[key];
			return {
				name: gift.name[locale],
				description: gift.description[locale],
				imageUrl: `/demo/${gift.image}`,
				url: `https://www.heureka.cz/?h%5Bfraze%5D=${encodeURIComponent(gift.search)}`,
				price: gift.price,
				category: gift.category[locale],
				priority: index === 0 || index === 7 ? 'high' : index === 14 ? 'low' : 'medium',
				state:
					wishlist.status === 'draft'
						? 'available'
						: index === 3 || index === 11
							? 'reserved'
							: index === 13
								? 'received'
								: 'available',
			};
		}),
	}));
}
